export const LOCATION_REPOSITORY = 'LOCATION_REPOSITORY';
export const CREATE_LOCATION_USE_CASE = 'CREATE_LOCATION_USE_CASE';
export const UPDATE_LOCATION_USE_CASE = 'UPDATE_LOCATION_USE_CASE';
export const DELETE_LOCATION_USE_CASE = 'DELETE_LOCATION_USE_CASE';
