export const PRODUCT_REPOSITORY = 'PRODUCT_REPOSITORY';
export const CREATE_PRODUCT_USE_CASE = 'CREATE_PRODUCT_USE_CASE';
export const UPDATE_PRODUCT_USE_CASE = 'UPDATE_PRODUCT_USE_CASE';
export const DELETE_PRODUCT_USE_CASE = 'DELETE_PRODUCT_USE_CASE';
